name: Debug DockerHub Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print all DockerHub-related secrets
        run: |
          echo ">> DOCKERHUB_USERNAME:  '${{ secrets.DOCKERHUB_USERNAME }}'"
          echo ">> DOCKERHUB_TOKEN:     '${{ secrets.DOCKERHUB_TOKEN }}'"
          echo ">> Available secrets:"
          printenv | grep -i dockerhub || true
