name: Build & Publish Services

on:
  push:
    branches: [ master ]
  workflow_dispatch:   # ← allows manual “Run workflow” in GitHub UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug: print DOCKERHUB_USERNAME
        run: |
          echo "⤷ will push to namespace ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ########################################
      # Auth service
      ########################################

      - name: Build Auth image
        run: |
          docker build \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }} \
            -f auth-service/Dockerfile \
            auth-service

      - name: Push Auth image
        if: success()
        run: |
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      ########################################
      # Backend service
      ########################################

      - name: Build Backend image
        run: |
          docker build \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} \
            -f backend/Dockerfile \
            backend

      - name: Push Backend image
        if: success()
        run: |
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
