name: Build & Publish Services

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ########################################
      # Auth service
      ########################################

      - name: Build & Push Auth image
        uses: docker/build-push-action@v4
        with:
          context: auth-service
          file: auth-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      ########################################
      # Backend service
      ########################################

      - name: Build & Push Backend image
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
