name: Build & Publish Services

# trigger on pushes to master or manual dispatch
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push both auth and backend in one go
      - name: Build & Push images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          # assume your Dockerfiles live in auth-service/ and backend/
          build-args: |
            AUTH_CONTEXT=auth-service
            BACKEND_CONTEXT=backend
          # if you need multiple contexts, you can do:
          # platforms: linux/amd64,linux/arm64
