# .github/workflows/docker-publish.yml
name: Build & Publish Auth Service

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker (daemon & Buildx)
        uses: docker/setup-docker@v3
        with:
          buildx: true
          start-docker: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --tag abrahambollarapu/auth-service:${{ github.sha }} \
            -f auth-service/Dockerfile \
            auth-service

      - name: Run Auth container
        run: |
          docker run -d --name auth-service-test -p 8001:8001 abrahambollarapu/auth-service:${{ github.sha }}
          for i in $(seq 1 10); do
            if [ "$(docker inspect --format='{{.State.Status}}' auth-service-test)" = "running" ]; then
              echo "✓ auth-service-test is running"
              break
            fi
            sleep 3
          done
          if [ "$(docker inspect --format='{{.State.Status}}' auth-service-test)" != "running" ]; then
            echo "❌ Container failed to start!"
            docker logs auth-service-test
            exit 1
          fi

      - name: Run Postman contract tests
        run: |
          npm install -g newman
          newman run postman/collection.json \
            --env-var "BASE_URL=http://localhost:8001" \
            --failfast

      - name: Stop & clean up test container
        if: always()
        run: |
          docker stop auth-service-test || true
          docker rm -f  auth-service-test || true

      - name: Push to Docker Hub
        if: success()
        run: |
          docker tag abrahambollarapu/auth-service:${{ github.sha }} abrahambollarapu/auth-service:latest
          docker push abrahambollarapu/auth-service:${{ github.sha }}
          docker push abrahambollarapu/auth-service:latest
