name: Build & Publish Auth Service

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options:
          - --privileged
          - --entrypoint
          - ''
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --tag abrahambollarapu/auth-service:${{ github.sha }} -f auth-service/Dockerfile auth-service

      - name: Run Auth container
        run: |
          docker run -d --name auth-service-test -p 8001:8001 abrahambollarapu/auth-service:${{ github.sha }}
          sleep 10

      - name: Run Postman contract tests
        run: |
          npm install -g newman
          newman run postman/collection.json --env-var "BASE_URL=http://localhost:8001"

      - name: Stop test container
        run: docker stop auth-service-test

      - name: Push to Docker Hub
        if: success()
        run: |
          docker tag abrahambollarapu/auth-service:${{ github.sha }} abrahambollarapu/auth-service:latest
          docker push abrahambollarapu/auth-service:${{ github.sha }}
          docker push abrahambollarapu/auth-service:latest
