name: Build & Publish Auth Service

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx & cache
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Auth image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --tag abrahambollarapu/auth-service:${{ github.sha }} \
            --load \
            -f auth-service/Dockerfile \
            auth-service
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run Auth container (healthchecks enforced)
        run: |
          docker run -d --name auth-service-test -p 8001:8001 abrahambollarapu/auth-service:${{ github.sha }}
          # Wait until HEALTHCHECK passes
          docker wait --interval=5s --timeout=60s auth-service-test

      - name: Run Postman contract tests
        run: |
          npm install -g newman
          newman run postman/collection.json \
            --env-var "BASE_URL=http://localhost:8001" \
            --failfast --bail

      - name: Teardown container
        if: always()
        run: |
          docker stop auth-service-test || true
          docker rm -f auth-service-test || true

      - name: Push to Docker Hub
        if: success() && github.ref == 'refs/heads/master'
        run: |
          docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
          docker tag abrahambollarapu/auth-service:${{ github.sha }} abrahambollarapu/auth-service:latest
          docker push abrahambollarapu/auth-service:${{ github.sha }}
          docker push abrahambollarapu/auth-service:latest
